// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGMa3r-43RBFrJ4vGPiRo5it_-0_VPx0A',
    appId: '1:248265494952:web:74de429d20d67792400d9d',
    messagingSenderId: '248265494952',
    projectId: 'fandomverse-cfe67',
    authDomain: 'fandomverse-cfe67.firebaseapp.com',
    storageBucket: 'fandomverse-cfe67.firebasestorage.app',
    measurementId: 'G-77JQTH9YND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnaRWPxwSU5I_hyIDTK37phbC3LSC5rQo',
    appId: '1:248265494952:android:4d671cbfa03cab9e400d9d',
    messagingSenderId: '248265494952',
    projectId: 'fandomverse-cfe67',
    storageBucket: 'fandomverse-cfe67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCduB7jWiAK0yxPnWa6SKfOQ-uXvBfZBLM',
    appId: '1:248265494952:ios:f97115d694b0f133400d9d',
    messagingSenderId: '248265494952',
    projectId: 'fandomverse-cfe67',
    storageBucket: 'fandomverse-cfe67.firebasestorage.app',
    iosBundleId: 'com.fandomverse.fandomVerse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGMa3r-43RBFrJ4vGPiRo5it_-0_VPx0A',
    appId: '1:248265494952:web:3c4d2471b3a6d903400d9d',
    messagingSenderId: '248265494952',
    projectId: 'fandomverse-cfe67',
    authDomain: 'fandomverse-cfe67.firebaseapp.com',
    storageBucket: 'fandomverse-cfe67.firebasestorage.app',
    measurementId: 'G-EJS0TRL97R',
  );
}
